export const INITIAL_INVOICES = [
  {
    id: "1/01/2024",
    date: "2024-01-15",
    sentDate: "2024-01-15",
    client: "Acme Corp",
    amount: 20000,
    tax: 4600,
    vatRate: 23,
    status: "Zapłacona",
    pdfUrl: null,
    dueDate: "2024-02-15",
    representativeName: "Anna Kowalska",
    representativeEmail: "anna.kowalska@acme.com",
    representativeGender: "female",
  },
  {
    id: "2/01/2024",
    date: "2024-01-20",
    sentDate: "2024-01-20",
    client: "TechStart Inc",
    amount: 12800,
    tax: 2944,
    vatRate: 23,
    status: "Przeterminowana",
    pdfUrl: "drive.google.com/file/123",
    dueDate: "2024-02-05",
    representativeName: "Piotr Nowak",
    representativeEmail: "piotr.nowak@techstart.com",
    representativeGender: "male",
  },
  {
    id: "3/01/2024",
    date: "2024-01-25",
    sentDate: "2024-01-25",
    client: "Global Solutions",
    amount: 30000,
    tax: 6900,
    vatRate: 23,
    status: "Zapłacona",
    pdfUrl: "drive.google.com/file/124",
    dueDate: "2024-02-25",
    representativeName: "Maria Wiśniewska",
    representativeEmail: "maria.wisniewska@global.com",
    representativeGender: "female",
  },
  {
    id: "4/02/2024",
    date: "2024-02-01",
    sentDate: null,
    client: "Innovation Labs",
    amount: 16800,
    tax: 3864,
    vatRate: 23,
    status: "Stworzona",
    pdfUrl: null,
    dueDate: "2024-03-01",
    representativeName: "Tomasz Zieliński",
    representativeEmail: "tomasz.zielinski@innovation.com",
    representativeGender: "male",
  },
]

export const INITIAL_EXPENSES = [
  { id: 1, date: "2024-01-10", description: "Czynsz biura", amount: 8000, category: "Operacyjne", pdfUrl: null },
  {
    id: 2,
    date: "2024-01-15",
    description: "Kampania marketingowa",
    amount: 6000,
    category: "Marketing",
    pdfUrl: "drive.google.com/file/exp1",
  },
  {
    id: 3,
    date: "2024-01-20",
    description: "Subskrypcje oprogramowania",
    amount: 3200,
    category: "Subskrypcje",
    pdfUrl: null,
  },
  {
    id: 4,
    date: "2024-01-25",
    description: "Zakup sprzętu",
    amount: 12800,
    category: "Sprzęt",
    pdfUrl: "drive.google.com/file/exp2",
  },
  { id: 5, date: "2024-02-01", description: "Koszty podróży", amount: 2600, category: "Podróże", pdfUrl: null },
]

export const INITIAL_OFFERS = [
  {
    id: "OF-001",
    title: "Projekt strony internetowej - Acme Corp",
    client: "Acme Corp",
    amount: 25000,
    createdDate: "2024-01-10",
    sentDate: "2024-01-12",
    expirationDate: "2024-02-12",
    status: "Wysłana",
    googleDocsUrl: "docs.google.com/document/123",
    daysToExpiration: 5,
  },
  {
    id: "OF-002",
    title: "Aplikacja mobilna - TechStart",
    client: "TechStart Inc",
    amount: 45000,
    createdDate: "2024-01-15",
    sentDate: "2024-01-18",
    expirationDate: "2024-02-18",
    status: "Zaakceptowana",
    googleDocsUrl: "docs.google.com/document/124",
    daysToExpiration: 11,
  },
  {
    id: "OF-003",
    title: "Konsultacje IT - Global Solutions",
    client: "Global Solutions",
    amount: 15000,
    createdDate: "2024-02-01",
    sentDate: null,
    expirationDate: "2024-03-01",
    status: "Szkic",
    googleDocsUrl: "docs.google.com/document/125",
    daysToExpiration: 23,
  },
]

export const INITIAL_RECURRING_PAYMENTS = [
  {
    id: 1,
    name: "Adobe Creative Suite",
    amount: 299,
    frequency: "Miesięcznie",
    nextPayment: "2024-02-15",
    category: "Subskrypcje",
    active: true,
  },
  {
    id: 2,
    name: "Hosting serwera",
    amount: 150,
    frequency: "Miesięcznie",
    nextPayment: "2024-02-20",
    category: "Operacyjne",
    active: true,
  },
  {
    id: 3,
    name: "Ubezpieczenie biznesowe",
    amount: 800,
    frequency: "Miesięcznie",
    nextPayment: "2024-02-25",
    category: "Ubezpieczenia",
    active: false,
  },
]

export const INVOICE_STATUSES = ["Stworzona", "Wysłana", "Zapłacona", "Przeterminowana"]

export const EXPENSE_CATEGORIES = ["Operacyjne", "Marketing", "Subskrypcje", "Sprzęt", "Podróże"]

export const RECURRING_FREQUENCIES = ["Miesięcznie", "Kwartalnie", "Rocznie"]

export const RECURRING_CATEGORIES = ["Subskrypcje", "Operacyjne", "Ubezpieczenia"] 